/* ============================================
   121212.events — Event Data
   Add one entry per event.
   Key = unique event ID.
   ============================================ */

const EVENTS_DATA = [

  /* ── Atlanta ── */
  {
    id:       'atl-afrotech-2026',
    name:     'AfroTech ATL 2026',
    city:     'Atlanta', state: 'GA', citySlug: 'atlanta',
    venue:    'Georgia World Congress Center',
    address:  '285 Andrew Young International Blvd NW, Atlanta, GA',
    date:     'Apr 12, 2026', dateSort: '2026-04-12',
    time:     '9:00 AM – 6:00 PM',
    price:    '$75', free: false,
    emoji:    '💻', category: 'Tech', catSlug: 'tech',
    featured: true,
    description: 'The South\'s premier Black tech conference. Three floors of panels, demos, and real networking — 90%+ Black attendees. Expect keynotes from founders, VCs, and engineers building the next wave of culture-forward technology.',
    tags: ['Tech', 'Networking', 'Innovation', 'Black Excellence'],
    ticketUrl: '#',
    hub: 'atlanta.121212.community',
  },
  {
    id:       'atl-juneteenth-2026',
    name:     'Juneteenth Block Party',
    city:     'Atlanta', state: 'GA', citySlug: 'atlanta',
    venue:    'Piedmont Park',
    address:  '400 Park Dr NE, Atlanta, GA',
    date:     'Jun 19, 2026', dateSort: '2026-06-19',
    time:     '12:00 PM – 9:00 PM',
    price:    'Free', free: true,
    emoji:    '✊', category: 'Culture', catSlug: 'culture',
    featured: true,
    description: 'ATL\'s biggest annual Juneteenth celebration. Live music, Black vendors, food trucks, kids zone, and community programming. A full day of freedom, food, and family.',
    tags: ['Culture', 'Community', 'Free', 'Family'],
    ticketUrl: '#',
    hub: 'atlanta.121212.community',
  },
  {
    id:       'atl-trap-gospel-2026',
    name:     'Trap Gospel Live',
    city:     'Atlanta', state: 'GA', citySlug: 'atlanta',
    venue:    'Fox Theatre',
    address:  '660 Peachtree St NE, Atlanta, GA',
    date:     'May 3, 2026', dateSort: '2026-05-03',
    time:     '7:00 PM – 10:00 PM',
    price:    '$45', free: false,
    emoji:    '🎵', category: 'Music', catSlug: 'music',
    featured: false,
    description: 'Where ATL gospel meets trap soul. An evening of spirit-filled performances in one of Atlanta\'s most iconic venues. Expect tears, fire, and full-house energy.',
    tags: ['Music', 'Gospel', 'Live Performance'],
    ticketUrl: '#',
    hub: 'atlanta.121212.community',
  },
  {
    id:       'atl-biz-expo-2026',
    name:     'Black Entrepreneurs Expo',
    city:     'Atlanta', state: 'GA', citySlug: 'atlanta',
    venue:    'AmericasMart',
    address:  '240 Peachtree St NW, Atlanta, GA',
    date:     'May 17, 2026', dateSort: '2026-05-17',
    time:     '10:00 AM – 5:00 PM',
    price:    '$20', free: false,
    emoji:    '💼', category: 'Business', catSlug: 'business',
    featured: false,
    description: 'A full-day expo connecting Black founders, investors, and consumers. Vendor hall, pitch competition, mentorship tables, and access to capital conversations.',
    tags: ['Business', 'Entrepreneurship', 'Networking', 'Pitch'],
    ticketUrl: '#',
    hub: 'atlanta.121212.community',
  },
  {
    id:       'atl-film-fest-2026',
    name:     'ATL Black Film Fest',
    city:     'Atlanta', state: 'GA', citySlug: 'atlanta',
    venue:    'Landmark Midtown Art Cinema',
    address:  '931 Monroe Dr NE, Atlanta, GA',
    date:     'May 31, 2026', dateSort: '2026-05-31',
    time:     '6:00 PM – 11:00 PM',
    price:    '$15', free: false,
    emoji:    '🎬', category: 'Film', catSlug: 'film',
    featured: false,
    description: 'Three nights of short films, features, and docs by and about Black creatives. Opening night reception. Director Q&As after every screening.',
    tags: ['Film', 'Art', 'Culture', 'Indie'],
    ticketUrl: '#',
    hub: 'atlanta.121212.community',
  },
  {
    id:       'atl-hair-expo-2026',
    name:     'Natural Hair & Beauty Expo',
    city:     'Atlanta', state: 'GA', citySlug: 'atlanta',
    venue:    'Atlanta Marriott Marquis',
    address:  '265 Peachtree Center Ave, Atlanta, GA',
    date:     'Apr 26, 2026', dateSort: '2026-04-26',
    time:     '10:00 AM – 6:00 PM',
    price:    'Free', free: true,
    emoji:    '💆', category: 'Wellness', catSlug: 'wellness',
    featured: false,
    description: 'The largest natural hair expo in the South. 100+ Black-owned beauty vendors, live styling demos, product sampling, panel discussions on scalp health and hair growth.',
    tags: ['Beauty', 'Wellness', 'Hair', 'Free', 'Black-Owned'],
    ticketUrl: '#',
    hub: 'atlanta.121212.community',
  },

  /* ── Chicago ── */
  {
    id:       'chi-blues-soul-2026',
    name:     'Chicago Blues & Soul Festival',
    city:     'Chicago', state: 'IL', citySlug: 'chicago',
    venue:    'Grant Park',
    address:  '337 E Randolph St, Chicago, IL',
    date:     'Jun 7, 2026', dateSort: '2026-06-07',
    time:     '12:00 PM – 10:00 PM',
    price:    'Free', free: true,
    emoji:    '🎸', category: 'Music', catSlug: 'music',
    featured: true,
    description: 'Chicago\'s annual celebration of the music that built this city. Three stages, two days, thirty artists. Blues, soul, R&B, and gospel on the lakefront.',
    tags: ['Music', 'Blues', 'Soul', 'Free', 'Outdoor'],
    ticketUrl: '#',
    hub: 'chicago.121212.community',
  },
  {
    id:       'chi-bronzeville-art-2026',
    name:     'Bronzeville Art Walk',
    city:     'Chicago', state: 'IL', citySlug: 'chicago',
    venue:    'Bronzeville District',
    address:  '4700 S King Dr, Chicago, IL',
    date:     'May 10, 2026', dateSort: '2026-05-10',
    time:     '11:00 AM – 7:00 PM',
    price:    'Free', free: true,
    emoji:    '🎨', category: 'Art', catSlug: 'art',
    featured: false,
    description: 'An afternoon walking tour through Bronzeville\'s gallery row. Over 20 Black-owned studios and galleries open their doors. Original work from over 60 local artists.',
    tags: ['Art', 'Gallery', 'Free', 'Outdoor', 'Walking'],
    ticketUrl: '#',
    hub: 'chicago.121212.community',
  },
  {
    id:       'chi-biz-brunch-2026',
    name:     'Black Business Brunch',
    city:     'Chicago', state: 'IL', citySlug: 'chicago',
    venue:    'The Promontory',
    address:  '5311 S Lake Park Ave, Chicago, IL',
    date:     'Apr 5, 2026', dateSort: '2026-04-05',
    time:     '10:00 AM – 1:00 PM',
    price:    '$35', free: false,
    emoji:    '☕', category: 'Business', catSlug: 'business',
    featured: false,
    description: 'Sunday morning, serious conversations. 80 Black business owners in one room. Curated small-table sessions, a featured keynote, and a meal worth staying for.',
    tags: ['Business', 'Networking', 'Brunch', 'Community'],
    ticketUrl: '#',
    hub: 'chicago.121212.community',
  },
  {
    id:       'chi-step-afrika-2026',
    name:     'Step Afrika! Live',
    city:     'Chicago', state: 'IL', citySlug: 'chicago',
    venue:    'Chicago Theatre',
    address:  '175 N State St, Chicago, IL',
    date:     'May 24, 2026', dateSort: '2026-05-24',
    time:     '7:30 PM',
    price:    '$55', free: false,
    emoji:    '💃', category: 'Culture', catSlug: 'culture',
    featured: false,
    description: 'The internationally acclaimed African-American stepping company brings their flagship production to Chicago. Power, precision, and an unmistakable cultural heartbeat.',
    tags: ['Dance', 'Culture', 'Live Performance', 'African'],
    ticketUrl: '#',
    hub: 'chicago.121212.community',
  },
  {
    id:       'chi-food-fest-2026',
    name:     'South Side Food Festival',
    city:     'Chicago', state: 'IL', citySlug: 'chicago',
    venue:    'Washington Park',
    address:  '5531 S Martin Luther King Dr, Chicago, IL',
    date:     'Jun 14, 2026', dateSort: '2026-06-14',
    time:     '11:00 AM – 8:00 PM',
    price:    'Free', free: true,
    emoji:    '🍽', category: 'Food', catSlug: 'food',
    featured: false,
    description: 'Thirty Black-owned food vendors representing the full breadth of South Side cuisine — jerk chicken, soul food classics, West African dishes, and artisan desserts.',
    tags: ['Food', 'Free', 'Black-Owned', 'Community', 'Outdoor'],
    ticketUrl: '#',
    hub: 'chicago.121212.community',
  },
  {
    id:       'chi-comedy-2026',
    name:     'Midwest Black Comedy Night',
    city:     'Chicago', state: 'IL', citySlug: 'chicago',
    venue:    'Laugh Factory Chicago',
    address:  '3175 N Broadway, Chicago, IL',
    date:     'Apr 18, 2026', dateSort: '2026-04-18',
    time:     '8:00 PM',
    price:    '$25', free: false,
    emoji:    '🎤', category: 'Comedy', catSlug: 'comedy',
    featured: false,
    description: 'A sold-out staple. Six Black comedians, no filter, two hours of uninterrupted laughter. Opening acts from Chicago\'s best emerging stand-up scene.',
    tags: ['Comedy', 'Stand-Up', 'Live', 'Nightlife'],
    ticketUrl: '#',
    hub: 'chicago.121212.community',
  },

  /* ── Houston ── */
  {
    id:       'hou-biz-expo-2026',
    name:     'H-Town Black Business Expo',
    city:     'Houston', state: 'TX', citySlug: 'houston',
    venue:    'George R. Brown Convention Center',
    address:  '1001 Avenida De Las Americas, Houston, TX',
    date:     'Apr 19, 2026', dateSort: '2026-04-19',
    time:     '9:00 AM – 5:00 PM',
    price:    '$30', free: false,
    emoji:    '💼', category: 'Business', catSlug: 'business',
    featured: true,
    description: 'Houston\'s largest gathering of Black entrepreneurs, investors, and economic power brokers. Vendor marketplace, live pitches, and capital access programming.',
    tags: ['Business', 'Entrepreneurship', 'Houston', 'Capital'],
    ticketUrl: '#',
    hub: null,
  },
  {
    id:       'hou-afrofuturism-2026',
    name:     'Houston Afrofuturism Arts Showcase',
    city:     'Houston', state: 'TX', citySlug: 'houston',
    venue:    'The Houston Museum of African American Culture',
    address:  '4807 Caroline St, Houston, TX',
    date:     'May 8, 2026', dateSort: '2026-05-08',
    time:     '6:00 PM – 10:00 PM',
    price:    '$20', free: false,
    emoji:    '🌌', category: 'Art', catSlug: 'art',
    featured: false,
    description: 'An immersive evening of Afrofuturist visual art, sound design, and performance. Fourteen Houston-based artists reimagining the future through a Black lens.',
    tags: ['Art', 'Afrofuturism', 'Performance', 'Culture'],
    ticketUrl: '#',
    hub: null,
  },
  {
    id:       'hou-soul-rb-2026',
    name:     'H-Town Soul & R&B Night',
    city:     'Houston', state: 'TX', citySlug: 'houston',
    venue:    'White Oak Music Hall',
    address:  '2915 N Main St, Houston, TX',
    date:     'May 22, 2026', dateSort: '2026-05-22',
    time:     '8:00 PM',
    price:    '$35', free: false,
    emoji:    '🎵', category: 'Music', catSlug: 'music',
    featured: false,
    description: 'Houston\'s homegrown R&B and neo-soul talent in a single unforgettable evening. Six acts, one stage, Third Coast energy from open to close.',
    tags: ['Music', 'R&B', 'Soul', 'Live', 'Third Coast'],
    ticketUrl: '#',
    hub: null,
  },

  /* ── Washington D.C. ── */
  {
    id:       'dc-cbc-culture-2026',
    name:     'CBC Arts & Culture Night',
    city:     'Washington D.C.', state: 'DC', citySlug: 'dc',
    venue:    'The Howard Theatre',
    address:  '620 T St NW, Washington, DC',
    date:     'Jun 5, 2026', dateSort: '2026-06-05',
    time:     '7:00 PM – 11:00 PM',
    price:    '$50', free: false,
    emoji:    '🏛', category: 'Culture', catSlug: 'culture',
    featured: true,
    description: 'An annual celebration hosted in D.C.\'s legendary Howard Theatre. Live performances, gallery installations, and conversations about Black art and political power.',
    tags: ['Culture', 'Politics', 'Art', 'DC', 'History'],
    ticketUrl: '#',
    hub: null,
  },
  {
    id:       'dc-fashion-week-2026',
    name:     'DC Black Fashion Week',
    city:     'Washington D.C.', state: 'DC', citySlug: 'dc',
    venue:    'Union Market',
    address:  '1309 5th St NE, Washington, DC',
    date:     'May 22, 2026', dateSort: '2026-05-22',
    time:     '6:00 PM – 10:00 PM',
    price:    '$40', free: false,
    emoji:    '👗', category: 'Fashion', catSlug: 'fashion',
    featured: false,
    description: 'Five nights of runway shows, pop-up markets, and styling workshops featuring emerging Black designers from D.C., Baltimore, and Philadelphia.',
    tags: ['Fashion', 'Design', 'Runway', 'Black Designers'],
    ticketUrl: '#',
    hub: null,
  },
  {
    id:       'dc-howard-arts-2026',
    name:     'Howard University Arts Expo',
    city:     'Washington D.C.', state: 'DC', citySlug: 'dc',
    venue:    'Howard University Cramton Auditorium',
    address:  '2455 6th St NW, Washington, DC',
    date:     'Apr 11, 2026', dateSort: '2026-04-11',
    time:     '10:00 AM – 5:00 PM',
    price:    '$25', free: false,
    emoji:    '📚', category: 'Education', catSlug: 'education',
    featured: false,
    description: 'A showcase of student and faculty work from the Howard University College of Arts & Sciences. Paintings, sculpture, digital media, film, and spoken word.',
    tags: ['Education', 'Art', 'HBCU', 'Youth', 'Culture'],
    ticketUrl: '#',
    hub: null,
  },

  /* ── Miami ── */
  {
    id:       'mia-afro-carib-2026',
    name:     'Afro-Caribbean Music Festival',
    city:     'Miami', state: 'FL', citySlug: 'miami',
    venue:    'Bayfront Park Amphitheater',
    address:  '301 Biscayne Blvd, Miami, FL',
    date:     'May 31, 2026', dateSort: '2026-05-31',
    time:     '2:00 PM – 11:00 PM',
    price:    'Free', free: true,
    emoji:    '🌴', category: 'Music', catSlug: 'music',
    featured: true,
    description: 'Where Afrobeats meets reggae, dancehall, soca, and Haitian kompa. Miami\'s waterfront comes alive for a full day of diaspora music, food, and culture.',
    tags: ['Music', 'Caribbean', 'Afrobeats', 'Free', 'Outdoor', 'Diaspora'],
    ticketUrl: '#',
    hub: null,
  },
  {
    id:       'mia-black-art-2026',
    name:     'Miami Black Art Showcase',
    city:     'Miami', state: 'FL', citySlug: 'miami',
    venue:    'Wynwood Arts District',
    address:  'NW 2nd Ave & NW 24th St, Miami, FL',
    date:     'Apr 5, 2026', dateSort: '2026-04-05',
    time:     '6:00 PM – 11:00 PM',
    price:    '$25', free: false,
    emoji:    '🎨', category: 'Art', catSlug: 'art',
    featured: false,
    description: 'A curated evening walk through Wynwood\'s Black-owned galleries. Twelve artists, interactive installations, and collectors conversations alongside Miami\'s most vibrant street art.',
    tags: ['Art', 'Gallery', 'Culture', 'Miami', 'Nightlife'],
    ticketUrl: '#',
    hub: null,
  },
  {
    id:       'mia-haitian-heritage-2026',
    name:     'Haitian Heritage Month Festival',
    city:     'Miami', state: 'FL', citySlug: 'miami',
    venue:    'Little Haiti Cultural Complex',
    address:  '212 NE 59th Terrace, Miami, FL',
    date:     'May 17, 2026', dateSort: '2026-05-17',
    time:     '12:00 PM – 8:00 PM',
    price:    'Free', free: true,
    emoji:    '✊', category: 'Culture', catSlug: 'culture',
    featured: false,
    description: 'Celebrating the richness of Haitian culture in Miami. Traditional music, dance, art, food, and storytelling across three stages in the heart of Little Haiti.',
    tags: ['Culture', 'Haitian', 'Free', 'Community', 'Diaspora'],
    ticketUrl: '#',
    hub: null,
  },

  /* ── New Orleans ── */
  {
    id:       'nola-essence-prty-2026',
    name:     'Essence Festival Pre-Party',
    city:     'New Orleans', state: 'LA', citySlug: 'neworleans',
    venue:    'Preservation Hall',
    address:  '726 St Peter St, New Orleans, LA',
    date:     'Jun 28, 2026', dateSort: '2026-06-28',
    time:     '9:00 PM – 2:00 AM',
    price:    '$65', free: false,
    emoji:    '🎺', category: 'Music', catSlug: 'music',
    featured: true,
    description: 'The official warm-up to Essence Fest weekend. Live jazz, brass band, and special guests in the most iconic music venue in America. Advance tickets only. Always sells out.',
    tags: ['Music', 'Jazz', 'Brass Band', 'NOLA', 'Essence'],
    ticketUrl: '#',
    hub: null,
  },
  {
    id:       'nola-restaurant-week-2026',
    name:     'NOLA Black Restaurant Week Kickoff',
    city:     'New Orleans', state: 'LA', citySlug: 'neworleans',
    venue:    'Dooky Chase\'s Restaurant',
    address:  '2301 Orleans Ave, New Orleans, LA',
    date:     'May 3, 2026', dateSort: '2026-05-03',
    time:     '5:00 PM – 10:00 PM',
    price:    'Free', free: true,
    emoji:    '🍽', category: 'Food', catSlug: 'food',
    featured: false,
    description: 'The opening night of New Orleans\' weeklong celebration of Black culinary tradition. Pop-up tastings, chef conversations, and a historic venue that has fed civil rights leaders for 70 years.',
    tags: ['Food', 'Culinary', 'Black-Owned', 'Free', 'History'],
    ticketUrl: '#',
    hub: null,
  },
  {
    id:       'nola-second-line-2026',
    name:     'Second Line Sundays: Black Brass Showcase',
    city:     'New Orleans', state: 'LA', citySlug: 'neworleans',
    venue:    'Treme Neighborhood',
    address:  'St Claude Ave & Dumaine St, New Orleans, LA',
    date:     'Apr 26, 2026', dateSort: '2026-04-26',
    time:     '2:00 PM – 6:00 PM',
    price:    'Free', free: true,
    emoji:    '🎶', category: 'Music', catSlug: 'music',
    featured: false,
    description: 'A live second line parade through the Treme featuring five brass bands. The original Black neighborhood cultural tradition. Umbrellas and handkerchiefs provided.',
    tags: ['Music', 'Jazz', 'Second Line', 'Treme', 'Free', 'Outdoor'],
    ticketUrl: '#',
    hub: null,
  },

  /* ── Detroit ── */
  {
    id:       'det-elec-soul-2026',
    name:     'Detroit Electronic & Soul Festival',
    city:     'Detroit', state: 'MI', citySlug: 'detroit',
    venue:    'Hart Plaza',
    address:  '1 Hart Plaza, Detroit, MI',
    date:     'Jun 21, 2026', dateSort: '2026-06-21',
    time:     '12:00 PM – 12:00 AM',
    price:    'Free', free: true,
    emoji:    '🎵', category: 'Music', catSlug: 'music',
    featured: true,
    description: 'Detroit invented both techno and Motown. This festival celebrates both — and everything in between. Two stages on the riverfront, from classic soul to deep electronic sets rooted in Black musical tradition.',
    tags: ['Music', 'Electronic', 'Soul', 'Techno', 'Motown', 'Free'],
    ticketUrl: '#',
    hub: null,
  },
  {
    id:       'det-motown-tribute-2026',
    name:     'Motown Tribute Night',
    city:     'Detroit', state: 'MI', citySlug: 'detroit',
    venue:    'The Fillmore Detroit',
    address:  '2115 Woodward Ave, Detroit, MI',
    date:     'Apr 26, 2026', dateSort: '2026-04-26',
    time:     '7:30 PM',
    price:    '$40', free: false,
    emoji:    '🎙', category: 'Music', catSlug: 'music',
    featured: false,
    description: 'A full tribute evening to Motown\'s golden era. Live orchestra, singers performing the Supremes, Marvin Gaye, Stevie Wonder, and Temptations. Black tie encouraged.',
    tags: ['Music', 'Motown', 'Tribute', 'Live Orchestra', 'Detroit'],
    ticketUrl: '#',
    hub: null,
  },
  {
    id:       'det-black-tech-2026',
    name:     'Detroit Black Tech Summit',
    city:     'Detroit', state: 'MI', citySlug: 'detroit',
    venue:    'Detroit Pistons Performance Center',
    address:  '6201 Connor Ave, Detroit, MI',
    date:     'May 3, 2026', dateSort: '2026-05-03',
    time:     '9:00 AM – 5:00 PM',
    price:    '$45', free: false,
    emoji:    '💻', category: 'Tech', catSlug: 'tech',
    featured: false,
    description: 'Bringing Detroit\'s Black tech founders, engineers, and investors together. Half-day of panels, half-day of pitches. The summit that\'s helping rebuild Motown with code.',
    tags: ['Tech', 'Innovation', 'Startup', 'Detroit', 'Comeback'],
    ticketUrl: '#',
    hub: null,
  },

]

/* ── Category Definitions ── */
const EVENT_CATEGORIES = [
  { slug: 'music',     label: 'Music',       emoji: '🎵', count: 0 },
  { slug: 'business',  label: 'Business',    emoji: '💼', count: 0 },
  { slug: 'culture',   label: 'Culture',     emoji: '✊', count: 0 },
  { slug: 'art',       label: 'Art',         emoji: '🎨', count: 0 },
  { slug: 'tech',      label: 'Tech',        emoji: '💻', count: 0 },
  { slug: 'food',      label: 'Food',        emoji: '🍽', count: 0 },
  { slug: 'fashion',   label: 'Fashion',     emoji: '👗', count: 0 },
  { slug: 'wellness',  label: 'Wellness',    emoji: '✨', count: 0 },
  { slug: 'comedy',    label: 'Comedy',      emoji: '🎤', count: 0 },
  { slug: 'film',      label: 'Film',        emoji: '🎬', count: 0 },
  { slug: 'education', label: 'Education',   emoji: '📚', count: 0 },
  { slug: 'community', label: 'Community',   emoji: '🏘', count: 0 },
]

/* ── City Definitions ── */
const EVENT_CITIES = [
  { slug: 'atlanta',    label: 'Atlanta',         state: 'GA', emoji: '🏙' },
  { slug: 'chicago',    label: 'Chicago',          state: 'IL', emoji: '🌬' },
  { slug: 'houston',    label: 'Houston',          state: 'TX', emoji: '🤠' },
  { slug: 'dc',         label: 'Washington D.C.', state: 'DC', emoji: '🏛' },
  { slug: 'miami',      label: 'Miami',            state: 'FL', emoji: '🌴' },
  { slug: 'neworleans', label: 'New Orleans',      state: 'LA', emoji: '🎺' },
  { slug: 'detroit',    label: 'Detroit',          state: 'MI', emoji: '🎵' },
]
